# Generated by Django 4.2.6 on 2023-10-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='numbermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.PositiveSmallIntegerField()),
                ('num3', models.PositiveIntegerField()),
                ('num4', models.PositiveBigIntegerField()),
                ('num5', models.FloatField()),
                ('num6', models.DecimalField(decimal_places=3, max_digits=5)),
                ('num7', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
                ('marks', models.PositiveIntegerField()),
            ],
        ),
    ]
