# Generated by Django 4.2.6 on 2023-10-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='charmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char1', models.CharField(max_length=50)),
                ('char2', models.EmailField(max_length=254)),
                ('char3', models.GenericIPAddressField()),
                ('char4', models.SlugField()),
                ('char5', models.TextField(max_length=500)),
                ('char6', models.JSONField()),
                ('char7', models.URLField()),
                ('char8', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='datemodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('date2', models.TimeField()),
                ('date3', models.DateTimeField()),
                ('date4', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='filemodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='')),
            ],
        ),
    ]
